### ISSUE TITLE
Issue in Safari

### ISSUE THREAD

**Issue by ctants** [exupero/saveSvgAsPng#100] opened 2016-09-09 23:56 UTC
I didn't see it noted anywhere, but in Safari (all versions), instead of downloading the png it loads it in the browser window. Is this a known issue? Is there any workaround for this?

**Comment by sheriferson** [comment] 2016-09-10 18:15
Yes, it seems to be an unfortunate stable problem with Safari - see #37.

**Comment by ctants** [comment] 2016-09-11 00:29
ok, bad Safari! Is it possible to open the png at least in an new tab?
I've added
`a.target = "_blank";`
 to line 259 but it has no effect.

**Comment by exupero** [comment] 2016-10-05 19:14
Closing as duplicate of #37.

**Closed as completed by exupero** 2016-10-05 19:14 UTC
