### ISSUE TITLE
CSS perpective don't work in chrome

### ISSUE THREAD

**Issue by 2extream** [exupero/saveSvgAsPng#146] opened 2017-10-16 07:17 UTC
Hi, i just work on some interesting project, where peaople can designe they own sport field. And after they finish there is option to save designe as image. I use SVG and your script for saving SVG as PNG, but there is problem in chrome and opera. In firefox and edge everything is fine, image is saved as expected, but in chrome image is saved like there is no perspective. Please look at images. 
You can see images: 
1.png is from program, 
2.png is saved from firefox and 
3.png is saved from Chrome.
Can you help me to solve this problem?
![1](https://user-images.githubusercontent.com/6499469/31599412-8eac6242-b252-11e7-8411-2063e2591446.png)
![2](https://user-images.githubusercontent.com/6499469/31599413-8ecd15c8-b252-11e7-825b-06bf218e9e4e.png)
![3](https://user-images.githubusercontent.com/6499469/31599414-8eede00a-b252-11e7-8a9e-d1e86f5d7cc0.png)

Thanks in advance!

**Comment by exupero** [comment] 2017-10-16 12:03
That looks like a fun app!

I doubt that there's anything this lib can do to fix the problem you've found, as it sounds like a problem with Webkit support for perspective CSS when writing the SVG image to canvas.

Do you have a minimal reproduction of the problem where I could see the sort of code you're working with?

**Comment by 2extream** [comment] 2017-10-16 12:10
Hi, 
Thank you for interesting in resolving my problem!
Here is link where you can try app: https://podne-obloge.com/bergo/index.php
Create some sport field you want and try to save img in FF and Chrome.
And in your inline demo app http://exupero.org/saveSvgAsPng/
you can try to put this code in attachment, 
[test.txt](https://github.com/exupero/saveSvgAsPng/files/1387336/test.txt)
and you will have same problem with perspective.
It is strange, like Chrome dont see it, when i took image created from chrom and in photoshop add just pesrpective to that image i got exactly what i need... :(

**Comment by exupero** [comment] 2018-05-14 23:58
I'm closing this, since I don't think this library can do anything about the problem. If you find evidence that this bug can be worked around, feel free to re-open.

**Closed as completed by exupero** 2018-05-14 23:58 UTC
Labels: browser bug
